FEAT: Closed #20 Changed Vagrantfile to clone our repo, install all needed items as stated in CA3/Part1 and run our CA2/Part2 application using Gradle 8.6.

diff --git a/CA3/Part2/Vagrantfile b/CA3/Part2/Vagrantfile
--- a/CA3/Part2/Vagrantfile
+++ b/CA3/Part2/Vagrantfile
@@ -7,7 +7,7 @@ Vagrant.configure("2") do |config|
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update -y
     sudo apt-get install -y iputils-ping avahi-daemon libnss-mdns unzip \
-        openjdk-11-jdk-headless
+        openjdk-17-jdk-headless
     # ifconfig
   SHELL
 
@@ -19,7 +19,7 @@ Vagrant.configure("2") do |config|
     db.vm.network "private_network", ip: "192.168.56.11"
 
     # We want to access H2 console from the host using port 8082
-    # We want to connet to the H2 server using port 9092
+    # We want to connect to the H2 server using port 9092
     db.vm.network "forwarded_port", guest: 8082, host: 8082
     db.vm.network "forwarded_port", guest: 9092, host: 9092
 
@@ -29,10 +29,7 @@ Vagrant.configure("2") do |config|
     SHELL
 
     # The following provision shell will run ALWAYS so that we can execute the H2 server process
-    # This could be done in a different way, for instance, setiing H2 as as service, like in the following link:
-    # How to setup java as a service in ubuntu: http://www.jcgonzalez.com/ubuntu-16-java-service-wrapper-example
-    #
-    # To connect to H2 use: jdbc:h2:tcp://192.168.33.11:9092/./jpadb
+    # This could be done in a different way, for instance, setting H2 as a service
     db.vm.provision "shell", :run => 'always', inline: <<-SHELL
       java -cp ./h2*.jar org.h2.tools.Server -web -webAllowOthers -tcp -tcpAllowOthers -ifNotExists > ~/out.txt &
     SHELL
@@ -40,36 +37,48 @@ Vagrant.configure("2") do |config|
 
   #============
   # Configurations specific to the webserver VM
+
+  #Name of VM
   config.vm.define "web" do |web|
     web.vm.box = "ubuntu/bionic64"
     web.vm.hostname = "web"
+    #IP address of VM
     web.vm.network "private_network", ip: "192.168.56.10"
 
-    # We set more ram memmory for this VM
+    # We set more RAM memory for this VM
     web.vm.provider "virtualbox" do |v|
       v.memory = 1024
     end
 
-    # We want to access tomcat from the host using port 8080
+    # We want to access Tomcat from the host using port 8080
     web.vm.network "forwarded_port", guest: 8080, host: 8080
 
-    web.vm.provision "shell", inline: <<-SHELL, privileged: false
-      # sudo apt-get install git -y
-      # sudo apt-get install nodejs -y
-      # sudo apt-get install npm -y
-      # sudo ln -s /usr/bin/nodejs /usr/bin/node
-      sudo apt install -y tomcat9 tomcat9-admin
-      # If you want to access Tomcat admin web page do the following:
-      # Edit /etc/tomcat9/tomcat-users.xml
-      # uncomment tomcat-users and add manager-gui to tomcat user
+    web.vm.provision "shell", inline: <<-SHELL, privileged: true
+      # Use set -e command to exit if any command fails
+      set -e
 
-      # Change the following command to clone your own repository!
-      git clone https://bitbucket.org/pssmatos/tut-basic-gradle.git
-      cd tut-basic-gradle
+      #Install required items like specified in CA3/Part1
+
+      #Install Git
+      sudo apt install -y git
+
+      #Install Gradle 8.6
+      wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
+      sudo mkdir /opt/gradle
+      sudo unzip -d /opt/gradle gradle-8.6-bin.zip
+      echo "export GRADLE_HOME=/opt/gradle/gradle-8.6" >> ~/.bashrc
+      echo "export PATH=$PATH:$GRADLE_HOME/bin" >> ~/.bashrc
+      source ~/.bashrc
+
+      #Clone repository, go to project root and change permissions of gradle wrapper
+      git clone https://github.com/sepsilva/devops-23-24-PSM-1231869
+      cd devops-23-24-PSM-1231869/CA2/Part2/react-and-spring-data-rest-basic
       chmod u+x gradlew
+
+      #Build the project and run it
       ./gradlew clean build
-      # To deploy the war file to tomcat9 do the following command:
-      sudo cp ./build/libs/basic-0.0.1-SNAPSHOT.war /var/lib/tomcat9/webapps
+      nohup ./gradlew bootRun > /home/vagrant/spring-boot-app.log 2>&1 &
+
     SHELL
   end
 end
